title: "John Doe"
description: "Développeur Full Stack & Designer"
email: "john@example.com"
github: "johndoe"
linkedin: "johndoe"
twitter: "johndoe"

# Build settings
plugins:
  - jekyll-feed

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
