title: Alexis Bord
email: votre.email@exemple.com
description: Élève ingénieur en Data & IA à Polytechnique Montréal. Recherche de stage de 6 mois en France - Mai 2026.
url: "https://alexisbord.github.io"
baseurl: ""

# Liens de navigation
header_pages:
  - index.md
  - projects.md

# Thème de base
theme: minima