title: "Alexis Bord"
hero_title: "Recherche <br> de stage"   # Grand titre affiché sur l'image
hero_tagline: "6 mois à partir de mai"
hero_image: "dark_lab_cut.png"
description: "Étudiant en data et intelligence artificielle"
about: ""
email: "alexis.bord094@gmail.com"
location: "Paris, France"
github: "alexisbord"
linkedin: "alexis-bord/"

# Build settings
plugins:
  - jekyll-feed

# Sass
sass:
  sass_dir: _sass
  style: compressed

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
